-- Disposable local harness for B2.1. It uses Supabase Auth's actual auth.users.
create table public.tenants (
  id bigint primary key,
  activo boolean not null default true,
  dominio text,
  nombre text
);

create table public.empresas_afiliadas (
  id bigint generated by default as identity primary key,
  tenant_id bigint references public.tenants(id),
  codigo text not null,
  activa boolean not null default true
);

create table public.usuarios (
  id bigint generated by default as identity primary key,
  email text not null unique,
  rol text not null default 'cliente',
  user_id text,
  empresa_codigo text,
  tenant_id bigint default 1 references public.tenants(id)
);

create table public.usuario_tenant_roles (
  id bigint generated by default as identity primary key,
  user_id text not null,
  tenant_id bigint not null references public.tenants(id),
  rol text not null,
  created_at timestamptz not null default now(),
  unique (user_id, tenant_id)
);

insert into public.tenants (id, activo, dominio, nombre) values
  (1, true, 'guepack.com', 'Guepack'),
  (2, true, 'tenant2.example.com', 'Tenant 2'),
  (4, true, 'tenant4.example.com', 'Tenant 4'),
  (5, true, 'CIAM.GUEPACK.COM', 'CIAM');

insert into public.empresas_afiliadas (tenant_id, codigo, activa)
values (1, 'ACME', true), (2, 'BETA', true);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.usuarios, public.usuario_tenant_roles, public.tenants, public.empresas_afiliadas to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
