BEGIN;

-- ============================================================================
-- 1. Outbox durable para iniciar la asignación
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pedidos_programados_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  ronda INTEGER NOT NULL DEFAULT 1,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  intentos INTEGER NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  procesado_en TIMESTAMPTZ,
  reclamado_en TIMESTAMPTZ,
  reclamado_por UUID,
  ultimo_error TEXT,
  CONSTRAINT pedidos_programados_outbox_pedido_key UNIQUE (pedido_id),
  CONSTRAINT pedidos_programados_outbox_pedido_fk
    FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id) ON DELETE CASCADE,
  CONSTRAINT pedidos_programados_outbox_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT pedidos_programados_outbox_estado_chk
    CHECK (estado IN ('pendiente', 'procesando', 'procesado')),
  CONSTRAINT pedidos_programados_outbox_ronda_chk CHECK (ronda > 0),
  CONSTRAINT pedidos_programados_outbox_intentos_chk CHECK (intentos >= 0)
);

CREATE INDEX IF NOT EXISTS pedidos_programados_outbox_pendientes_idx
  ON public.pedidos_programados_outbox (estado, creado_en, id)
  WHERE estado IN ('pendiente', 'procesando');

ALTER TABLE public.pedidos_programados_outbox ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.pedidos_programados_outbox
FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.pedidos_programados_outbox TO service_role;

GRANT USAGE, SELECT
ON SEQUENCE public.pedidos_programados_outbox_id_seq TO service_role;

-- ============================================================================
-- 2. Throttle diario para alertas de configuración
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.alertas_configuracion_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  fecha_dia DATE NOT NULL,
  motivo TEXT NOT NULL,
  enviado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT alertas_configuracion_log_pedido_fecha_key
    UNIQUE (pedido_id, fecha_dia),
  CONSTRAINT alertas_configuracion_log_pedido_fk
    FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id) ON DELETE CASCADE,
  CONSTRAINT alertas_configuracion_log_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT alertas_configuracion_log_motivo_chk
    CHECK (
      motivo IN (
        'CONFIGURACION_FALTANTE',
        'HORARIO_APERTURA_FALTANTE',
        'ZONA_HORARIA_FALTANTE'
      )
    )
);

CREATE INDEX IF NOT EXISTS alertas_configuracion_log_tenant_fecha_idx
  ON public.alertas_configuracion_log (tenant_id, fecha_dia DESC);

ALTER TABLE public.alertas_configuracion_log ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.alertas_configuracion_log
FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT
ON TABLE public.alertas_configuracion_log TO service_role;

GRANT USAGE, SELECT
ON SEQUENCE public.alertas_configuracion_log_id_seq TO service_role;

-- ============================================================================
-- 3. Evaluación y activación atómica del lote
-- ============================================================================

CREATE OR REPLACE FUNCTION public.activar_pedidos_programados_lote(
  p_limite INTEGER DEFAULT 100,
  p_ahora TIMESTAMPTZ DEFAULT statement_timestamp()
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_lock_obtenido BOOLEAN;
  v_limite INTEGER;
  v_evaluados INTEGER := 0;
  v_activados INTEGER := 0;
  v_configuraciones_invalidas INTEGER := 0;
  v_fechas_invalidas INTEGER := 0;
  v_pedidos_activados JSONB := '[]'::JSONB;
  v_incidencias JSONB := '[]'::JSONB;
  v_alerta_nueva BOOLEAN;
  v_fecha_alerta DATE;
  v_registro RECORD;
BEGIN
  IF p_ahora IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '22004',
      MESSAGE = 'MOMENTO_ACTUAL_REQUERIDO';
  END IF;

  v_limite := LEAST(GREATEST(COALESCE(p_limite, 100), 1), 500);

  v_lock_obtenido :=
    pg_catalog.pg_try_advisory_xact_lock(
      pg_catalog.hashtextextended('activar_pedidos_programados', 0)
    );

  IF NOT v_lock_obtenido THEN
    RETURN jsonb_build_object(
      'success', TRUE,
      'omitido_por_ejecucion_en_curso', TRUE,
      'evaluados', 0,
      'activados', 0,
      'configuraciones_invalidas', 0,
      'fechas_invalidas', 0,
      'pedidos_activados', '[]'::JSONB,
      'incidencias', '[]'::JSONB
    );
  END IF;

  SELECT count(*)
  INTO v_evaluados
  FROM public.pedidos AS pedido
  WHERE pedido.estado = 'Programado';

  FOR v_registro IN
    SELECT pedido.id AS pedido_id, pedido.tenant_id, pedido.fecha
    FROM public.pedidos AS pedido
    WHERE pedido.estado = 'Programado'
      AND (
        pedido.fecha IS NULL
        OR pedido.fecha !~ '^\d{4}-\d{2}-\d{2}$'
        OR to_char(to_date(pedido.fecha, 'YYYY-MM-DD'), 'YYYY-MM-DD')
          <> pedido.fecha
      )
    ORDER BY pedido.id
    LIMIT v_limite
  LOOP
    v_fechas_invalidas := v_fechas_invalidas + 1;
    RAISE LOG
      'PEDIDO_PROGRAMADO_FECHA_INVALIDA pedido_id=% tenant_id=% fecha=%',
      v_registro.pedido_id,
      v_registro.tenant_id,
      coalesce(v_registro.fecha, 'NULL');
  END LOOP;

  FOR v_registro IN
    SELECT
      pedido.id AS pedido_id,
      pedido.tenant_id,
      tenant.zona_horaria,
      configuracion.tenant_id AS configuracion_tenant_id,
      configuracion.horario_apertura,
      CASE
        WHEN configuracion.tenant_id IS NULL
          THEN 'CONFIGURACION_FALTANTE'
        WHEN configuracion.horario_apertura IS NULL
          THEN 'HORARIO_APERTURA_FALTANTE'
        WHEN tenant.zona_horaria IS NULL
          THEN 'ZONA_HORARIA_FALTANTE'
      END AS motivo
    FROM public.pedidos AS pedido
    LEFT JOIN public.tenants AS tenant ON tenant.id = pedido.tenant_id
    LEFT JOIN public.configuracion AS configuracion
      ON configuracion.tenant_id = pedido.tenant_id
    WHERE pedido.estado = 'Programado'
      AND (
        configuracion.tenant_id IS NULL
        OR configuracion.horario_apertura IS NULL
        OR tenant.zona_horaria IS NULL
      )
    ORDER BY pedido.id
    LIMIT v_limite
  LOOP
    v_configuraciones_invalidas := v_configuraciones_invalidas + 1;
    RAISE LOG
      'PEDIDO_PROGRAMADO_CONFIGURACION_INVALIDA pedido_id=% tenant_id=% motivo=%',
      v_registro.pedido_id,
      v_registro.tenant_id,
      v_registro.motivo;

    v_fecha_alerta :=
      (p_ahora AT TIME ZONE coalesce(v_registro.zona_horaria, 'UTC'))::DATE;
    v_alerta_nueva := FALSE;

    INSERT INTO public.alertas_configuracion_log (
      pedido_id, tenant_id, fecha_dia, motivo, enviado_en
    )
    VALUES (
      v_registro.pedido_id,
      v_registro.tenant_id,
      v_fecha_alerta,
      v_registro.motivo,
      p_ahora
    )
    ON CONFLICT ON CONSTRAINT alertas_configuracion_log_pedido_fecha_key
    DO NOTHING
    RETURNING TRUE INTO v_alerta_nueva;

    v_incidencias := v_incidencias || jsonb_build_array(
      jsonb_build_object(
        'pedido_id', v_registro.pedido_id,
        'tenant_id', v_registro.tenant_id,
        'motivo', v_registro.motivo,
        'debe_enviar_alerta', coalesce(v_alerta_nueva, FALSE)
      )
    );
  END LOOP;

  FOR v_registro IN
    SELECT
      pedido.id AS pedido_id,
      pedido.tenant_id,
      pedido.metodo_pago,
      pedido.pago_verificado,
      pedido.fecha,
      configuracion.horario_apertura,
      tenant.zona_horaria
    FROM public.pedidos AS pedido
    INNER JOIN public.tenants AS tenant ON tenant.id = pedido.tenant_id
    INNER JOIN public.configuracion AS configuracion
      ON configuracion.tenant_id = pedido.tenant_id
    WHERE pedido.estado = 'Programado'
      AND pedido.repartidor IS NULL
      AND pedido.fecha ~ '^\d{4}-\d{2}-\d{2}$'
      AND to_char(to_date(pedido.fecha, 'YYYY-MM-DD'), 'YYYY-MM-DD')
        = pedido.fecha
      AND configuracion.horario_apertura IS NOT NULL
      AND tenant.zona_horaria IS NOT NULL
      AND p_ahora >= (
        (
          to_date(pedido.fecha, 'YYYY-MM-DD')
          + configuracion.horario_apertura
        ) AT TIME ZONE tenant.zona_horaria
      )
      AND (
        lower(btrim(coalesce(pedido.metodo_pago, '')))
          NOT IN ('tarjeta', 'transferencia')
        OR pedido.pago_verificado IS TRUE
      )
    ORDER BY pedido.id
    FOR UPDATE OF pedido SKIP LOCKED
    LIMIT v_limite
  LOOP
    UPDATE public.pedidos AS pedido
    SET estado = 'Pendiente', ronda_asignacion = 0
    WHERE pedido.id = v_registro.pedido_id
      AND pedido.estado = 'Programado'
      AND pedido.repartidor IS NULL;

    IF NOT FOUND THEN
      CONTINUE;
    END IF;

    INSERT INTO public.pedidos_programados_outbox (
      pedido_id, tenant_id, ronda, estado, creado_en, actualizado_en
    )
    VALUES (
      v_registro.pedido_id,
      v_registro.tenant_id,
      1,
      'pendiente',
      p_ahora,
      p_ahora
    )
    ON CONFLICT ON CONSTRAINT pedidos_programados_outbox_pedido_key
    DO NOTHING;

    v_activados := v_activados + 1;
    v_pedidos_activados := v_pedidos_activados || jsonb_build_array(
      jsonb_build_object(
        'pedido_id', v_registro.pedido_id,
        'tenant_id', v_registro.tenant_id,
        'estado', 'Pendiente'
      )
    );
  END LOOP;

  RETURN jsonb_build_object(
    'success', TRUE,
    'omitido_por_ejecucion_en_curso', FALSE,
    'evaluados', v_evaluados,
    'activados', v_activados,
    'configuraciones_invalidas', v_configuraciones_invalidas,
    'fechas_invalidas', v_fechas_invalidas,
    'pedidos_activados', v_pedidos_activados,
    'incidencias', v_incidencias
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.activar_pedidos_programados_lote(
  INTEGER, TIMESTAMPTZ
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.activar_pedidos_programados_lote(
  INTEGER, TIMESTAMPTZ
) TO service_role;

-- ============================================================================
-- 4. Reclamación segura de trabajos de asignación
-- ============================================================================

CREATE OR REPLACE FUNCTION public.reclamar_asignaciones_programadas(
  p_reclamado_por UUID,
  p_limite INTEGER DEFAULT 100,
  p_ahora TIMESTAMPTZ DEFAULT statement_timestamp()
)
RETURNS TABLE (
  outbox_id BIGINT,
  pedido_id BIGINT,
  tenant_id BIGINT,
  ronda INTEGER,
  intentos INTEGER
)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_limite INTEGER;
BEGIN
  IF p_reclamado_por IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '22004', MESSAGE = 'RECLAMADO_POR_REQUERIDO';
  END IF;
  IF p_ahora IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '22004', MESSAGE = 'MOMENTO_ACTUAL_REQUERIDO';
  END IF;

  v_limite := LEAST(GREATEST(COALESCE(p_limite, 100), 1), 500);

  UPDATE public.pedidos_programados_outbox AS outbox
  SET
    estado = 'pendiente',
    reclamado_en = NULL,
    reclamado_por = NULL,
    actualizado_en = p_ahora
  WHERE outbox.estado = 'procesando'
    AND outbox.reclamado_en < p_ahora - INTERVAL '5 minutes';

  RETURN QUERY
  WITH candidatos AS (
    SELECT outbox.id
    FROM public.pedidos_programados_outbox AS outbox
    WHERE outbox.estado = 'pendiente'
    ORDER BY outbox.creado_en, outbox.id
    FOR UPDATE SKIP LOCKED
    LIMIT v_limite
  ),
  reclamados AS (
    UPDATE public.pedidos_programados_outbox AS outbox
    SET
      estado = 'procesando',
      intentos = outbox.intentos + 1,
      reclamado_en = p_ahora,
      reclamado_por = p_reclamado_por,
      actualizado_en = p_ahora,
      ultimo_error = NULL
    FROM candidatos
    WHERE outbox.id = candidatos.id
    RETURNING
      outbox.id,
      outbox.pedido_id,
      outbox.tenant_id,
      outbox.ronda,
      outbox.intentos
  )
  SELECT
    reclamados.id,
    reclamados.pedido_id,
    reclamados.tenant_id,
    reclamados.ronda,
    reclamados.intentos
  FROM reclamados
  ORDER BY reclamados.id;
END;
$function$;

REVOKE ALL ON FUNCTION public.reclamar_asignaciones_programadas(
  UUID, INTEGER, TIMESTAMPTZ
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.reclamar_asignaciones_programadas(
  UUID, INTEGER, TIMESTAMPTZ
) TO service_role;

-- ============================================================================
-- 5. Resolución de trabajos reclamados
-- ============================================================================

CREATE OR REPLACE FUNCTION public.resolver_asignacion_programada(
  p_outbox_id BIGINT,
  p_reclamado_por UUID,
  p_exitosa BOOLEAN,
  p_error TEXT DEFAULT NULL,
  p_ahora TIMESTAMPTZ DEFAULT statement_timestamp()
)
RETURNS BOOLEAN
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF p_outbox_id IS NULL
     OR p_reclamado_por IS NULL
     OR p_exitosa IS NULL
     OR p_ahora IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '22004', MESSAGE = 'PARAMETROS_DE_RESOLUCION_INCOMPLETOS';
  END IF;

  IF p_exitosa THEN
    UPDATE public.pedidos_programados_outbox AS outbox
    SET
      estado = 'procesado',
      procesado_en = p_ahora,
      actualizado_en = p_ahora,
      reclamado_en = NULL,
      reclamado_por = NULL,
      ultimo_error = NULL
    WHERE outbox.id = p_outbox_id
      AND outbox.estado = 'procesando'
      AND outbox.reclamado_por = p_reclamado_por;
  ELSE
    UPDATE public.pedidos_programados_outbox AS outbox
    SET
      estado = 'pendiente',
      actualizado_en = p_ahora,
      reclamado_en = NULL,
      reclamado_por = NULL,
      ultimo_error = left(coalesce(p_error, 'Error desconocido'), 2000)
    WHERE outbox.id = p_outbox_id
      AND outbox.estado = 'procesando'
      AND outbox.reclamado_por = p_reclamado_por;
  END IF;

  RETURN FOUND;
END;
$function$;

REVOKE ALL ON FUNCTION public.resolver_asignacion_programada(
  BIGINT, UUID, BOOLEAN, TEXT, TIMESTAMPTZ
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.resolver_asignacion_programada(
  BIGINT, UUID, BOOLEAN, TEXT, TIMESTAMPTZ
) TO service_role;

-- ============================================================================
-- 6. Defensa adicional: solo se acepta un pedido Pendiente
-- ============================================================================

CREATE OR REPLACE FUNCTION public.aceptar_pedido_atomico(p_pedido_id BIGINT)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  usuario_id UUID;
  repartidor_nombre TEXT;
  repartidor_tenant_id BIGINT;
  ganancia_base_config NUMERIC;
  ganancia_por_km_config NUMERIC;
  ganancia_diaria_config NUMERIC;
  pedido_tenant_id BIGINT;
  pedido_repartidor TEXT;
  pedido_estado TEXT;
  pedido_km NUMERIC;
  pedido_precio NUMERIC;
  pedido_zona TEXT;
  ganancia_calculada NUMERIC;
  filas_afectadas INTEGER;
BEGIN
  usuario_id := auth.uid();
  IF usuario_id IS NULL THEN
    RAISE EXCEPTION 'Se requiere una sesión autenticada'
      USING ERRCODE = '28000';
  END IF;

  SELECT
    r.nombre,
    r.tenant_id,
    COALESCE(r.ganancia_base, 20),
    COALESCE(r.ganancia_por_km, 5),
    COALESCE(r.ganancia_tarifa_diaria, 40)
  INTO
    repartidor_nombre,
    repartidor_tenant_id,
    ganancia_base_config,
    ganancia_por_km_config,
    ganancia_diaria_config
  FROM public.usuarios AS u
  INNER JOIN public.repartidores AS r
    ON LOWER(r.email) = LOWER(u.email)
   AND r.tenant_id = u.tenant_id
  WHERE u.user_id = usuario_id::TEXT
    AND u.rol = 'repartidor'
    AND r.disponible IS TRUE
  LIMIT 1;

  IF repartidor_nombre IS NULL THEN
    RAISE EXCEPTION
      'El usuario autenticado no corresponde a un repartidor disponible'
      USING ERRCODE = '42501';
  END IF;

  SELECT
    p.tenant_id,
    p.repartidor,
    p.estado,
    COALESCE(p.km_recorridos, 0),
    COALESCE(p.precio, 0),
    COALESCE(p.zona, '')
  INTO
    pedido_tenant_id,
    pedido_repartidor,
    pedido_estado,
    pedido_km,
    pedido_precio,
    pedido_zona
  FROM public.pedidos AS p
  WHERE p.id = p_pedido_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El pedido solicitado no existe'
      USING ERRCODE = 'P0002';
  END IF;
  IF pedido_tenant_id IS DISTINCT FROM repartidor_tenant_id THEN
    RAISE EXCEPTION 'El repartidor no pertenece al tenant del pedido'
      USING ERRCODE = '42501';
  END IF;
  IF pedido_estado IS DISTINCT FROM 'Pendiente' THEN
    RETURN 0;
  END IF;
  IF pedido_repartidor IS NOT NULL THEN
    RETURN 0;
  END IF;

  IF pedido_zona ILIKE '%Tarifa diaria%' THEN
    ganancia_calculada := ROUND(
      pedido_precio * ganancia_diaria_config / 100
    );
  ELSE
    ganancia_calculada := ROUND(
      ganancia_base_config + pedido_km * ganancia_por_km_config
    );
  END IF;

  UPDATE public.pedidos
  SET
    repartidor = repartidor_nombre,
    asignacion_automatica = TRUE,
    ganancia_repartidor = ganancia_calculada
  WHERE id = p_pedido_id
    AND repartidor IS NULL
    AND estado = 'Pendiente';

  GET DIAGNOSTICS filas_afectadas = ROW_COUNT;
  RETURN filas_afectadas;
END;
$function$;

REVOKE ALL ON FUNCTION public.aceptar_pedido_atomico(BIGINT)
FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.aceptar_pedido_atomico(BIGINT)
TO authenticated;

-- ============================================================================
-- 7. Cron cada minuto usando el secreto existente de Vault
-- ============================================================================

DO $cron_setup$
DECLARE
  v_service_role_key_existe BOOLEAN;
  v_job_id BIGINT;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM vault.secrets AS secreto
    WHERE secreto.name = 'cron_service_role_key'
  )
  INTO v_service_role_key_existe;

  IF NOT v_service_role_key_existe THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'VAULT_CRON_SERVICE_ROLE_KEY_FALTANTE',
      HINT = 'El secreto cron_service_role_key debe existir en Vault.';
  END IF;

  SELECT trabajo.jobid
  INTO v_job_id
  FROM cron.job AS trabajo
  WHERE trabajo.jobname = 'activar-pedidos-programados-cada-minuto'
  LIMIT 1;

  IF v_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(v_job_id);
  END IF;

  PERFORM cron.schedule(
    'activar-pedidos-programados-cada-minuto',
    '* * * * *',
    $job$
    SELECT net.http_post(
      url := 'https://zkrnjdsnuyjaxxnluzmn.supabase.co/functions/v1/activar-pedidos-programados',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization',
        'Bearer ' || (
          SELECT secreto.decrypted_secret
          FROM vault.decrypted_secrets AS secreto
          WHERE secreto.name = 'cron_service_role_key'
          ORDER BY secreto.created_at DESC
          LIMIT 1
        )
      ),
      body := '{}'::jsonb
    );
    $job$
  );
END;
$cron_setup$;

COMMIT;
