CREATE TABLE IF NOT EXISTS public.verificaciones_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etapa TEXT NOT NULL,
  codigo TEXT,
  mensaje TEXT CHECK (mensaje IS NULL OR char_length(mensaje) <= 300),
  telefono_masked TEXT CHECK (
    telefono_masked IS NULL
    OR telefono_masked ~ '^[0-9]{6}\*{4}[0-9]{2}$'
  ),
  hostname TEXT NOT NULL,
  standalone BOOLEAN NOT NULL DEFAULT FALSE,
  user_agent TEXT CHECK (user_agent IS NULL OR char_length(user_agent) <= 200),
  usuario_id UUID,
  tenant_id BIGINT REFERENCES public.tenants(id) ON DELETE SET NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS verificaciones_log_etapa_creado_en_idx
  ON public.verificaciones_log (etapa, creado_en DESC);

ALTER TABLE public.verificaciones_log ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.verificaciones_log FROM PUBLIC, anon, authenticated;
GRANT INSERT ON TABLE public.verificaciones_log TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON TABLE public.verificaciones_log TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.verificaciones_log_id_seq TO anon, authenticated;

DROP POLICY IF EXISTS "Anon y usuarios registran verificaciones" ON public.verificaciones_log;
CREATE POLICY "Anon y usuarios registran verificaciones"
  ON public.verificaciones_log
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    (auth.uid() IS NULL AND usuario_id IS NULL)
    OR
    (auth.uid() IS NOT NULL AND (usuario_id IS NULL OR usuario_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Superadmins leen verificaciones" ON public.verificaciones_log;
CREATE POLICY "Superadmins leen verificaciones"
  ON public.verificaciones_log
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.usuarios AS administrador
      WHERE administrador.user_id::TEXT = auth.uid()::TEXT
        AND administrador.es_superadmin IS TRUE
    )
  );

DROP POLICY IF EXISTS "Superadmins actualizan verificaciones" ON public.verificaciones_log;
CREATE POLICY "Superadmins actualizan verificaciones"
  ON public.verificaciones_log
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.usuarios AS administrador
      WHERE administrador.user_id::TEXT = auth.uid()::TEXT
        AND administrador.es_superadmin IS TRUE
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.usuarios AS administrador
      WHERE administrador.user_id::TEXT = auth.uid()::TEXT
        AND administrador.es_superadmin IS TRUE
    )
  );

DROP POLICY IF EXISTS "Superadmins eliminan verificaciones" ON public.verificaciones_log;
CREATE POLICY "Superadmins eliminan verificaciones"
  ON public.verificaciones_log
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.usuarios AS administrador
      WHERE administrador.user_id::TEXT = auth.uid()::TEXT
        AND administrador.es_superadmin IS TRUE
    )
  );
