CREATE TABLE public.campanas_reactivacion_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  email TEXT NOT NULL,
  segmento TEXT NOT NULL,
  cupon_codigo TEXT NOT NULL,
  enviado_en TIMESTAMPTZ,
  tenant_id BIGINT NOT NULL
    REFERENCES public.tenants(id)
    ON DELETE CASCADE,

  CONSTRAINT campanas_reactivacion_log_segmento_valido
    CHECK (segmento IN ('nunca_pidieron', 'inactivos')),

  CONSTRAINT campanas_reactivacion_log_email_no_vacio
    CHECK (btrim(email) <> ''),

  CONSTRAINT campanas_reactivacion_log_cupon_no_vacio
    CHECK (btrim(cupon_codigo) <> ''),

  CONSTRAINT campanas_reactivacion_log_usuario_segmento_unico
    UNIQUE (user_id, segmento)
);

CREATE INDEX campanas_reactivacion_log_tenant_segmento_idx
  ON public.campanas_reactivacion_log (tenant_id, segmento);

CREATE INDEX campanas_reactivacion_log_enviado_en_idx
  ON public.campanas_reactivacion_log (enviado_en);

COMMENT ON TABLE public.campanas_reactivacion_log IS
  'Registro e idempotencia de correos enviados por campanas de reactivacion.';

COMMENT ON COLUMN public.campanas_reactivacion_log.enviado_en IS
  'NULL mientras el destinatario esta reservado; se completa cuando Resend acepta el correo.';

ALTER TABLE public.campanas_reactivacion_log ENABLE ROW LEVEL SECURITY;

-- No se crean politicas para anon ni authenticated. La Edge Function usa service_role.
-- user_id es deliberadamente TEXT y no tiene FK a usuarios ni auth.users para conservar
-- el historial aunque posteriormente se elimine la cuenta.

CREATE OR REPLACE FUNCTION public.listar_clientes_reactivacion(
  p_segmento TEXT,
  p_tenant_id BIGINT DEFAULT NULL
)
RETURNS TABLE (
  user_id TEXT,
  email TEXT,
  nombre TEXT,
  tenant_id BIGINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    u.user_id::TEXT,
    btrim(u.email)::TEXT,
    NULLIF(btrim(u.nombre), '')::TEXT,
    u.tenant_id::BIGINT
  FROM public.usuarios AS u
  WHERE u.rol = 'cliente'
    AND u.user_id IS NOT NULL
    AND u.email IS NOT NULL
    AND btrim(u.email) <> ''
    AND u.tenant_id IS NOT NULL
    AND (
      p_tenant_id IS NULL
      OR u.tenant_id = p_tenant_id
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.campanas_reactivacion_log AS log
      WHERE log.user_id = u.user_id::TEXT
        AND log.segmento = p_segmento
    )
    AND (
      (
        p_segmento = 'nunca_pidieron'
        AND NOT EXISTS (
          SELECT 1
          FROM public.pedidos AS p
          WHERE p.user_id::TEXT = u.user_id::TEXT
        )
      )
      OR
      (
        p_segmento = 'inactivos'
        AND EXISTS (
          SELECT 1
          FROM public.pedidos AS p
          WHERE p.user_id::TEXT = u.user_id::TEXT
        )
        AND (
          SELECT MAX(p.created_at)
          FROM public.pedidos AS p
          WHERE p.user_id::TEXT = u.user_id::TEXT
        ) < now() - INTERVAL '7 days'
      )
    )
  ORDER BY u.tenant_id, u.user_id;
$$;

COMMENT ON FUNCTION public.listar_clientes_reactivacion(TEXT, BIGINT) IS
  'Obtiene clientes elegibles para una campana; debe invocarse exclusivamente con service_role.';

REVOKE ALL
  ON FUNCTION public.listar_clientes_reactivacion(TEXT, BIGINT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE
  ON FUNCTION public.listar_clientes_reactivacion(TEXT, BIGINT)
  TO service_role;
