CREATE TABLE IF NOT EXISTS public.pagos_saas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  periodo DATE NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  monto NUMERIC(12, 2) NOT NULL CHECK (monto >= 0),
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagado')),
  fecha_pago TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pagos_saas_tenant_fecha_idx
  ON public.pagos_saas (tenant_id, fecha_vencimiento DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'pagos_saas'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.pagos_saas;
  END IF;
END $$;

ALTER TABLE public.pagos_saas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Superadmins administran pagos SaaS" ON public.pagos_saas;
CREATE POLICY "Superadmins administran pagos SaaS"
  ON public.pagos_saas
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.user_id::TEXT = auth.uid()::TEXT
        AND usuarios.es_superadmin = TRUE
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.user_id::TEXT = auth.uid()::TEXT
        AND usuarios.es_superadmin = TRUE
    )
  );

DROP POLICY IF EXISTS "Administradores consultan pagos de su tenant" ON public.pagos_saas;
CREATE POLICY "Administradores consultan pagos de su tenant"
  ON public.pagos_saas
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.user_id::TEXT = auth.uid()::TEXT
        AND usuarios.rol = 'admin'
        AND usuarios.tenant_id = pagos_saas.tenant_id
    )
  );
